<script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
<script type="text/javascript" src="<?=$config('application.webroot') ?>/assets/vendors/bootstrap/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="<?=$config('application.webroot') ?>/assets/vendors/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?=$config('application.webroot') ?>/assets/vendors/bootbox/bootbox.all.min.js"></script>
<script type="text/javascript" src="<?=$config('application.webroot') ?>/assets/js/app.min.js"></script>