<!-- Fixed navbar -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
	<a class="navbar-brand" href="#">phpDummyMail</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarCollapse">
		<div class="btn-group group-enable-disable">
			<button class="btn btn-dark trigger-check-all" disabled>
				<span class="fa fa-check-square-o"></span>
			</button>
			<button class="btn btn-dark trigger-uncheck-all" disabled>
				<span class="fa fa-square-o"></span>
			</button>
		</div>
		<div class="btn-group">
			<button class="btn btn-dark trigger-remove" disabled>
				<span class="fa fa-trash"></span>
			</button>
		</div>
		<button class="btn btn-dark trigger-purge button-enable-disable" disabled>
			Purge mails
		</button>
		<button class="btn btn-dark trigger-mailcheck">
			<span class="fa fa-refresh"></span>
		</button>
	</div>
</nav>