<link rel="section" id="url-maillist" href="<?=$config('application.approot') ?>/maillist/grid" data-method="GET" />
<link rel="section" id="url-mailcheck" href="<?=$config('application.approot') ?>/mailcheck" data-method="GET" />
<link rel="section" id="url-mailpurge" href="<?=$config('application.approot') ?>/mailpurge" data-method="POST" />
<link rel="section" id="url-mailopen" href="<?=$config('application.approot') ?>/mailopen/content" data-method="NONE" data-target="IFRAME" />
<link rel="section" id="url-mailremove" href="<?=$config('application.approot') ?>/mailremove" data-method="POST" />
