<!DOCTYPE html>
<html>
    <head>
        <title><?=$title ?></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" type="text/css" href="<?=$config('application.webroot') ?>/assets/vendors/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="<?=$config('application.webroot') ?>/assets/css/custom.css" />
        <link rel="stylesheet" type="text/css" href="<?=$config('application.webroot') ?>/assets/vendors/font-awesome/css/font-awesome.min.css" />

        <link rel="section" id="url-mailcheck" href="<?=$config('application.approot') ?>/mailcheck" data-method="GET" />
        <link rel="section" id="url-mailpurge" href="<?=$config('application.approot') ?>/mailpurge" data-method="POST" />
        <link rel="section" id="url-mailopen" href="<?=$config('application.approot') ?>/mailopen/content" data-method="NONE" data-target="IFRAME" />
        <link rel="section" id="url-mailremove" href="<?=$config('application.approot') ?>/mailremove" data-method="POST" />
    </head>
    <body class="d-flex flex-column h-100">
        <header>
            <!-- Fixed navbar -->
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
                <a class="navbar-brand" href="#">phpDummyMail</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="btn-group group-enable-disable">
                        <button class="btn btn-dark trigger-check-all" disabled>
                            <span class="fa fa-check-square-o"></span>
                        </button>
                        <button class="btn btn-dark trigger-uncheck-all" disabled>
                            <span class="fa fa-square-o"></span>
                        </button>
                    </div>
                    <div class="btn-group">
                        <button class="btn btn-dark trigger-remove" disabled>
                            <span class="fa fa-trash"></span>
                        </button>
                    </div>
                    <button class="btn btn-dark trigger-purge button-enable-disable" disabled>
                        Purge mails
                    </button>
                    <button class="btn btn-dark trigger-mailcheck">
                        <span class="fa fa-refresh"></span>
                    </button>
                </div>
            </nav>
        </header>

        <!-- Begin page content -->
        <main role="main">
            <div class="container-fluid">
                <?=$layoutContent ?>
            </div>
        </main>


        <footer class="footer">
            <div class="text-right">Created by ReeStyle</div>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
        <script defer type="text/javascript" src="<?=$config('application.webroot') ?>/assets/vendors/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script defer type="text/javascript" src="<?=$config('application.webroot') ?>/assets/vendors/bootstrap/js/bootstrap.min.js"></script>
        <script defer type="text/javascript" src="<?=$config('application.webroot') ?>/assets/vendors/bootbox/bootbox.all.min.js"></script>
        <script type="text/javascript" src="<?=$config('application.webroot') ?>/assets/js/app.js"></script>
    </body>
</html>
