<!DOCTYPE html>
<html>
    <head>
        <title><?=$title ?></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <?php require __DIR__ . '/snippet/css.phtml' ?>
        <?php require __DIR__ . '/snippet/sourceurls.phtml' ?>
    </head>
    <body class="d-flex flex-column h-100">
        <header>
            <?php require __DIR__ . '/snippet/nav.phtml' ?>
        </header>

        <!-- Begin page content -->
        <main role="main">
            <div class="container-fluid">
                <?=$layoutContent ?>
            </div>
        </main>

        <footer class="footer">
            <div class="row">
                <div class="col-6">
                    <a href="<?=$config('application.approot') ?>/info/licenses" data-modal-type="license" class="trigger-modal-show">
                        View licenses
                    </a>
                </div>
                <div class="col-6 text-right">
                    Created by ReeStyle
                </div>
            </div>
        </footer>

        <?php require __DIR__ . '/snippet/js.phtml' ?>
    </body>
</html>
