<!DOCTYPE html>
<html>
<head>
	<title>Mailcontent</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" type="text/css" href="<?=$config('application.webroot') ?>/assets/vendors/bootstrap/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="<?=$config('application.webroot') ?>/assets/css/custom.css" />
	<link rel="stylesheet" type="text/css" href="<?=$config('application.webroot') ?>/assets/vendors/font-awesome/css/font-awesome.min.css" />
</head>
<body class="d-flex flex-column h-100">

<div class="container-fluid">
<?=$layoutContent ?>
</div>

<script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
<script type="text/javascript" src="<?=$config('application.webroot') ?>/assets/vendors/popper/popper.min.js"></script>
<script type="text/javascript" src="<?=$config('application.webroot') ?>/assets/vendors/bootstrap/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript" src="<?=$config('application.webroot') ?>/assets/vendors/bootstrap/js/bootstrap.min.js"></script>
<script type="text/javascript" src="<?=$config('application.webroot') ?>/assets/js/app.js"></script>

<script type="text/javascript">
    $(function () {
        function resetHeightIframe() {
            setTimeout(function () {
                window.parent.$('#mail-iframe').css('height', $('body').height());
            }, 150);
        }

        resetHeightIframe();

        $('.nav-link').on('click', resetHeightIframe);
        $('.nav-link:first').trigger('click');

        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

</body>
</html>
