<!DOCTYPE html>
<html>
<head>
	<title>Mailcontent</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" type="text/css" href="<?=$config('application.webroot') ?>/assets/vendors/bootstrap/css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="<?=$config('application.webroot') ?>/assets/css/custom.css" />
	<link rel="stylesheet" type="text/css" href="<?=$config('application.webroot') ?>/assets/vendors/font-awesome/css/font-awesome.min.css" />
</head>
<body class="d-flex flex-column h-100">

<div class="container-fluid">
<?=$layoutContent ?>
</div>

</body>
</html>
