<!DOCTYPE html>
<html>
<head>
	<title>Mailcontent</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<?php require __DIR__ . '/snippet/css.phtml' ?>
	<?php require __DIR__ . '/snippet/sourceurls.phtml' ?>
</head>
<body class="d-flex flex-column h-100">

<div class="container-fluid">
<?=$layoutContent ?>
</div>

<?php require __DIR__ . '/snippet/js.phtml' ?>

<script type="text/javascript">
    $(function () {
        function resetHeightIframe() {
            setTimeout(function () {
                window.parent.$('#mail-iframe').css('height', $('body').height());
            }, 150);
        }

        resetHeightIframe();

        $('.nav-link').on('click', resetHeightIframe);
        $('.nav-link:first').trigger('click');

        $('[data-toggle="tooltip"]').tooltip();
    });
</script>

</body>
</html>
