<div class="row" style="border-bottom: 1px #ccc solid; padding-bottom: 4px;">
    <div class="col-12">
        <div class="btn-group group-enable-disable">
            <button class="btn btn-dark trigger-check-all" disabled>
                <span class="fa fa-check-square-o"></span>
            </button>
            <button class="btn btn-dark trigger-uncheck-all" disabled>
                <span class="fa fa-square-o"></span>
            </button>
        </div>
        <div class="btn-group group-enable-disable">
            <button class="btn btn-dark trigger-delete" disabled>
                <span class="fa fa-trash"></span>
            </button>
        </div>
        <button class="btn btn-dark trigger-purge button-enable-disable" disabled>
            Purge mails
        </button>
        <button class="btn btn-dark trigger-mailcheck">
            <span class="fa fa-refresh"></span>
        </button>
    </div>
</div>
<div class="row">
    <div class="col-4 maillist-container" id="maillist-container">
    </div>
    <div class="col-8">
        <div class="text-muted">
            No mail selected
        </div>
    </div>
</div>