
<div class="row">
    <div class="col-4 maillist-container" id="maillist-container">
    </div>
    <div class="col-8 mail-display-container" id="mail-display-container">
        <div class="text-muted no-mail-message">
            No mail selected
        </div>
        <div class="mail-iframe">
            <iframe frameborder="0" id="mail-iframe" src="" style="height: 100%; width: 100%;"></iframe>
        </div>
    </div>
</div>