<?php  if(count($mails) === 0):?>
<div class="text-muted">No mails</div>
<?php  else: ?>
<?php  foreach ($mails as $mailId => $mail): ?>
<div class="row trigger-mail-open" data-mail-id="<?=$mailId ?>">
    <div class="col-1">
        <input type="checkbox" value="<?=$mailId ?>" class="trigger-mail-selection" />
    </div>
    <div class="col">
        <div class="row">
            <div class="col-8 text-muted small">
                From: <?=htmlspecialchars($mail['from']) ?><br />
                To: <?=htmlspecialchars($mail['to']) ?>
            </div>
            <div class="col text-muted small">
                Date:<br /> <?=$mail['date'] ?>
            </div>
        </div>
        <div class="small">
		    <?=$mail['subject'] ?>
        </div>
    </div>
    <div class="col-12" style="border-bottom: 1px #ccc dotted">

    </div>
</div>
<?php  endforeach ?>
<?php  endif ?>