<?php  if(count($mails) === 0):?>
<div class="text-muted">No mails</div>
<?php  else: ?>
<?php  foreach ($mails as $mailId => $mail): ?>
<div class="row trigger-mail-open" data-mail-id="<?=$mailId ?>">
    <div class="col-1">
        <input type="checkbox" value="<?=$mailId ?>" />
    </div>
    <div class="col">
        <div class="small">
            <div class="text-muted">
            From: <?=htmlspecialchars($mail['from']) ?><br />
            To: <?=htmlspecialchars($mail['to']) ?>
            </div>
		    <?=$mail['subject'] ?>
        </div>
    </div>
    <div class="col-12" style="border-bottom: 1px #ccc dotted">

    </div>
</div>
<?php  endforeach ?>
<?php  endif ?>